### ISSUE TITLE
If an input with name="action" exists, it will not be processed correctly

### ISSUE THREAD

**Issue by aiji42** [fregante/push-form#1]
## Overview

On my site, I have the following form.
```html
<form action="/p/customer-details">
  <input type="hidden" name="action" value="checkout">
  ...
</form>
```
In this case, the value that can be retrieved with `form.action` is the element itself with `name="action"`.
![スクリーンショット 2021-02-16 23 45 10](https://user-images.githubusercontent.com/6711766/108078645-48553c80-70b1-11eb-89d1-d02d8200661d.png)

Therefore, the URL of the submit destination cannot be established.

## Solution

You should use this method to access the `action` attribute.  
`form.getAttribute('action')`

![スクリーンショット 2021-02-16 23 51 44](https://user-images.githubusercontent.com/6711766/108079230-f234c900-70b1-11eb-8548-85b1599c6e35.png)

**Comment by fregante** [comment]
Thank you for the issue and PR!

Bad JavaScript APIs will never stop to amaze me. 

I’ll release a new version later today
